#!/usr/bin/env ruby

# This file should be located at .git/hooks/commit-msg

# cd project_dir
# cp hooks/commit-msg .git/hooks/commit-msg
# chmod u+x .git/hooks/commit-msg

message_file = ARGV[0]
message = File.read(message_file)

$regex = /([resolved|fixed]) #([0-9])* ([A-Z])\w+/

if !$regex.match(message)
  puts "[POLICY] Your message is not formatted correctly!"
  puts " "
  puts "Message format must be like:"
  puts "resolved #123 Case title (for features)"
  puts "fixed #123 Case title    (for bugs)"
  puts " "
  puts "First letter of 'Case title' must be capitalized!"
  exit 1
end
